### ISSUE TITLE
create a new bibtex tag for search during a new query

### ISSUE THREAD

**Issue by yilihong** [shiqiezi/google-scholar-citations#21]
It appears current program uses an index to search for the last bibtex entry found in the html. 

I am wondering, if I want to run this program every a few months to update the citation list, but do not want to go through all the html pages and write duplicate bibtex entries, the fastest maybe to create an additional bibtex tag for the google scholar citation ID (bolded):

@article{siering2013credence,
  title={Credence Goods and Online Product Reviews: An Exploration of the Product Type Concept in the Social Commerce Era},
  author={Siering, Michael and Muntermann, Jan},
  year={2013},
  **gscholarid = {ANQmKNTJGAcJ}**
}

This way, the new query could check for existing google scholar citation ID by parsing the bib file, and avoid duplicate entry that way.

By the way, such additional tags are also well supported and integrated in emacs's helm-bibtex (not sure about vim).

**Comment by liuml07** [comment]
This proposal sounds great! I'll pick this up later if no one contributes a patch. Thanks, @yilihong

**Comment by shiqiezi** [comment]
Hi @yilihong May I add you as a contributor so that you can directly push to this repo instead of forking and filing pull requests, if you'd like to work on this?

**Comment by yilihong** [comment]
@shiqiezi

Yes I'd be happy to. It's very useful to me personally as well. Thank you.

**Comment by yilihong** [comment]
@liuml07 @shiqiezi 

See here the pull request. Please test.
#23
